development:
  adapter: mysql
  database: vertada
  username: root
  password: atrac
  encoding: utf8
 
test:
  adapter: mysql
  database: funda_test
  username: root
  password: 
  encoding: utf8

production:
  adapter: mysql
  database: vertada
  username: root
  password: atrac
  encoding: utf8